server:
  port: 8002

spring:
  application:
    name: payment-provider-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: Abc1234%

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.springcloud.entities

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: payment8002
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 4
    lease-renewal-interval-in-seconds: 3
